# Generated by Django 3.2.8 on 2021-10-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('patient', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='assigned patient')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.room_id')),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
    ]
