# Generated by Django 3.2.8 on 2021-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
        migrations.AddField(
            model_name='room',
            name='sub_type',
            field=models.CharField(choices=[('AC_room', 'AC_room'), ('Non_AC_room', 'Non_AC_room')], default='Non_AC_room', max_length=11),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Normal_room', 'Normal_room'), ('Icu_room', 'Icu_room')], default='Normal_room', max_length=11),
        ),
    ]
