# Generated by Django 3.2.8 on 2021-10-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20211006_1559'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allocated_room',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.DeleteModel(
            name='room_id',
        ),
    ]
