# Generated by Django 3.2.8 on 2021-10-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20211006_1559'),
        ('patients', '0003_alter_patient_allocated_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allocated_room',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_patient', to='rooms.room'),
        ),
    ]
